INSERT INTO options (question_id, quiz_id, option)
VALUES (1,1,'Sydney'),
(1,1, 'Canberra'),
(1,1, 'Melbourne'),
(1,1, 'Brisbane'),
(2,1, 'Rwanda'),
(2,1, 'Ethiopia'),
(2,1, 'Kenya'),
(2,1, 'Tanzania'),
(3,1, 'Amazon'),
(3,1, 'Orinoco'),
(3,1, 'Parana'),
(3,1, 'Magdalena'),
(4,1, 'Mount Denali'),
(4,1, 'Mount Kilimanjaro'),
(4,1, 'Mount Everest'),
(4,1, 'Mount Aconcagua'),
(5,1, 'India'),
(5,1, 'China'),
(5,1, 'USA'),
(5,1, 'Russia');